# Generated by Django 5.0.2 on 2025-12-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
