# Generated by Django 5.0.2 on 2025-12-08 18:17

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_face_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='image_cutout',
            field=models.ImageField(upload_to=gallery.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='persongroup',
            name='cover_face',
            field=models.ImageField(blank=True, null=True, upload_to=gallery.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=gallery.models.get_file_path),
        ),
    ]
